# Generated by Django 2.1.4 on 2019-02-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190205_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pasta',
        ),
    ]
