# Generated by Django 2.1.4 on 2019-02-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_dinnerplatter_pasta_pizzatopping_subtopping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
    ]
