# Generated by Django 2.1.4 on 2019-02-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_dinnerplatter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
    ]
