# Generated by Django 2.1.4 on 2019-06-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190620_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='order',
        ),
        migrations.DeleteModel(
            name='PizzaTopping',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='order',
        ),
        migrations.DeleteModel(
            name='SubTopping',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(default='regular', max_length=20),
        ),
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Toppings'),
        ),
    ]
