# Generated by Django 2.1.4 on 2019-06-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20190620_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(choices=[('REG', 'Regular'), ('SIC', 'Sicilian')], max_length=3),
        ),
    ]
