# Generated by Django 2.1.4 on 2019-06-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20190620_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=10),
        ),
    ]
