# Generated by Django 2.1.4 on 2019-06-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20190620_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('topping_type', models.CharField(choices=[('cheese', 'Cheese'), ('1', '1 topping'), ('2', '2 toppings'), ('3', '3 toppings'), ('special', 'Special')], max_length=7)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
