# Generated by Django 2.1.4 on 2019-06-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20190620_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_type', models.CharField(choices=[('Cheese', 'Cheese'), ('1 Topping', '1 topping'), ('2 Toppings', '2 Toppings'), ('3 Toppings', '3 Toppings'), ('Special', 'Special')], max_length=10)),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
