# Generated by Django 2.1.4 on 2019-06-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_dinnerplatters_pasta_salads_subs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DinnerPlatters',
            new_name='DinnerPlatter',
        ),
        migrations.RenameModel(
            old_name='Salads',
            new_name='Salad',
        ),
        migrations.RenameModel(
            old_name='Subs',
            new_name='Sub',
        ),
    ]
