# Generated by Django 2.1.4 on 2019-06-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20190620_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_type', models.CharField(max_length=20)),
            ],
        ),
    ]
