# Generated by Django 2.1.4 on 2019-06-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_subextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='subextra',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
