# Generated by Django 2.1.4 on 2019-06-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_subextra_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='possible_extras',
            field=models.ManyToManyField(blank=True, related_name='available_on', to='orders.SubExtra'),
        ),
    ]
