# Generated by Django 2.1.4 on 2019-06-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_sub_possible_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='possible_extras',
            field=models.ManyToManyField(related_name='available_on', to='orders.SubExtra'),
        ),
    ]
